apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: api
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
        - name: backend
          image: backend:local
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_LINK
              value: postgresql://postgres:12345@db:5432/warehouse
          ports:
            - containerPort: 9111
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
              