version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: warehouse
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d warehouse" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s
    restart: unless-stopped

  rest-service:
    container_name: rest_service
    image: cr.yandex/crp0eri98ul6tprvn7sn/rest-service
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9111:9111"
    networks:
      - default
  frontend:
    container_name: react_app
    image: cr.yandex/crp0eri98ul6tprvn7sn/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    networks:
      - default
    environment:
      - REACT_APP_API_URL=http://rest-service:9111
    restart: unless-stopped

networks:
  default:
    driver: bridge