global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: [ "node_exporter:9100" ]
  - job_name: "rest-service"
    metrics_path: /metrics
    static_configs:
      - targets: [ "rest-service:9111" ]